version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - apt update && apt install -y python3-dev python3-pip
  pre_build:
    commands:
      - echo "Starting tests"
  build:
    commands:
      - python3 test.py
  post_build:
    commands:
      - echo "Build complete"