version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt update && apt install -y python3-dev python3-pip
      - pip3 install -r requirements.txt
  pre_build:
    commands:
      - echo "Starting tests"
  build:
    commands:
      - cd src
      - python3 test.py
  post_build:
    commands:
      - echo "Build complete"